CREATE TABLE pilot
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    age        INTEGER,
    CONSTRAINT pk_pilot PRIMARY KEY (id)
);